from graph import *
def creategraph_1 ():
 g = Graphs()
 addnode(g, node("A", 1, 20))
 addnode(g, node("B", 8, 17))
 addnode(g, node("C", 15, 20))
 addnode(g, node("D", 18, 15))
 addnode(g, node("E", 2, 4))
 addnode(g, node("F", 6, 5))
 addnode(g, node("G", 12, 12))
 addnode(g, node("H", 10, 3))
 addnode(g, node("I", 19, 1))
 addnode(g, node("J", 13, 5))
 addnode(g, node("K", 3, 15))
 addnode(g, node("L", 4, 10))
 addsegment(g, "AB", "A", "B")
 addsegment(g, "AE", "A", "E")
 addsegment(g, "AK", "A", "K")
 addsegment(g, "BA", "B", "A")
 addsegment(g, "BC", "B", "C")
 addsegment(g, "BF", "B", "F")
 addsegment(g, "BK", "B", "K")
 addsegment(g, "BG", "B", "G")
 addsegment(g, "CD", "C", "D")
 addsegment(g, "CG", "C", "G")
 addsegment(g, "DG", "D", "G")
 addsegment(g, "DH", "D", "H")
 addsegment(g, "DI", "D", "I")
 addsegment(g, "EF", "E", "F")
 addsegment(g, "FL", "F", "L")
 addsegment(g, "GB", "G", "B")
 addsegment(g, "GF", "G", "F")
 addsegment(g, "GH", "G", "H")
 addsegment(g, "ID", "I", "D")
 addsegment(g, "IJ", "I", "J")
 addsegment(g, "JI", "J", "I")
 addsegment(g, "KA", "K", "A")
 addsegment(g, "KL", "K", "L")
 addsegment(g, "LK", "L", "K")
 addsegment(g, "LF", "L", "F")

 #test adicional
 addnode(g, node("ja", 10, 20))
 addnode(g, node("jaja", 10, 40))
 addnode(g, node("ji", 0, 30))
 addnode(g, node("jiji", 5, 45))
 addsegment(g, "jajaji", "jaja", "ji")
 addsegment(g, "jija", "ji", "ja")
 addsegment(g, "jijijaja", "jiji", "jaja")
 addsegment(g, "jijija", "jiji", "ja")

 return g

print ("Probando el grafo...")
g = creategraph_1()
#g = load_graph_from_file("graph_data.txt")
'''plot(g)
plot_node(g, "C")
n = getclosest(g, 15, 5)
print(n.name)  # La respuesta debe ser J
n = getclosest(g, 8, 19)
print(n.name)  # La respuesta debe ser B'''